### ISSUE TITLE
Add max-width to main content block

### ISSUE THREAD

**Issue by julia-smith** [INN/umbrella-ipbs#16]
`.maincontent {
    max-width: 1400px;
    margin: 0 auto;
}`

**Comment by benlk** [comment]
Resolved in  af814b1

**Comment by benlk** [comment]
- [x] this
```css
#front-page {
   max-width: none;
}
```
